/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



package project_baru;



/**
 *
 * @author User
 */
public class dasbord extends javax.swing.JFrame {

    /**
     * Creates new form dasbord
     */
    public dasbord() {
   
        initComponents();
          this.setExtendedState(MAXIMIZED_BOTH);
         
        
        
    }
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_tavbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pn_sidebar = new javax.swing.JPanel();
        TbHoem = new javax.swing.JButton();
        TbHoem1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        TbReport = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        TbKos1 = new javax.swing.JButton();
        pn_utama = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setPreferredSize(new java.awt.Dimension(1195, 700));

        pn_tavbar.setBackground(new java.awt.Color(255, 235, 205));
        pn_tavbar.setForeground(new java.awt.Color(153, 153, 153));
        pn_tavbar.setPreferredSize(new java.awt.Dimension(700, 65));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Kuliner");

        javax.swing.GroupLayout pn_tavbarLayout = new javax.swing.GroupLayout(pn_tavbar);
        pn_tavbar.setLayout(pn_tavbarLayout);
        pn_tavbarLayout.setHorizontalGroup(
            pn_tavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_tavbarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(1060, Short.MAX_VALUE))
        );
        pn_tavbarLayout.setVerticalGroup(
            pn_tavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_tavbarLayout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        getContentPane().add(pn_tavbar, java.awt.BorderLayout.PAGE_START);

        pn_sidebar.setBackground(new java.awt.Color(255, 235, 205));
        pn_sidebar.setPreferredSize(new java.awt.Dimension(195, 355));

        TbHoem.setBackground(new java.awt.Color(245, 245, 220));
        TbHoem.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        TbHoem.setForeground(new java.awt.Color(0, 0, 0));
        TbHoem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hoome.png"))); // NOI18N
        TbHoem.setText("Home");
        TbHoem.setBorder(null);
        TbHoem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TbHoem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbHoemActionPerformed(evt);
            }
        });

        TbHoem1.setBackground(new java.awt.Color(245, 245, 220));
        TbHoem1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        TbHoem1.setForeground(new java.awt.Color(0, 0, 0));
        TbHoem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        TbHoem1.setText("Makanan");
        TbHoem1.setBorder(null);
        TbHoem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TbHoem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbHoem1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(245, 245, 220));
        jButton1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoutt.png"))); // NOI18N
        jButton1.setText("Logout");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TbReport.setBackground(new java.awt.Color(245, 245, 220));
        TbReport.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        TbReport.setForeground(new java.awt.Color(0, 0, 0));
        TbReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportt.png"))); // NOI18N
        TbReport.setText("About");
        TbReport.setBorder(null);
        TbReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TbReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbReportActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(245, 245, 220));
        jButton3.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Nama Anggota");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        TbKos1.setBackground(new java.awt.Color(255, 255, 255));
        TbKos1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        TbKos1.setForeground(new java.awt.Color(0, 0, 0));
        TbKos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/murah.png"))); // NOI18N
        TbKos1.setText("Pmbayaran");
        TbKos1.setBorder(null);
        TbKos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TbKos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbKos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_sidebarLayout = new javax.swing.GroupLayout(pn_sidebar);
        pn_sidebar.setLayout(pn_sidebarLayout);
        pn_sidebarLayout.setHorizontalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_sidebarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TbHoem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TbHoem, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(TbReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(TbKos1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        pn_sidebarLayout.setVerticalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_sidebarLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(TbHoem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TbHoem1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TbKos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TbReport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        getContentPane().add(pn_sidebar, java.awt.BorderLayout.LINE_START);

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.BorderLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pe.png"))); // NOI18N
        pn_utama.add(jLabel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_utama, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TbHoemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbHoemActionPerformed
        pn_utama.removeAll();
        pn_utama.add(new home());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_TbHoemActionPerformed

    private void TbHoem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbHoem1ActionPerformed
        pn_utama.removeAll();
        pn_utama.add(new makanan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_TbHoem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hide();
        login back = new login();
        back.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TbReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbReportActionPerformed
        pn_utama.removeAll();
        pn_utama.add(new about());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_TbReportActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TbKos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbKos1ActionPerformed
        pn_utama.removeAll();
        pn_utama.add(new pembayaran());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_TbKos1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dasbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dasbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dasbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dasbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dasbord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TbHoem;
    private javax.swing.JButton TbHoem1;
    private javax.swing.JButton TbKos1;
    private javax.swing.JButton TbReport;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pn_sidebar;
    private javax.swing.JPanel pn_tavbar;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
