/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project_baru;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class makanan extends javax.swing.JPanel {

    /**
     * Creates new form makanan
     */
    public makanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        sate = new javax.swing.JComboBox<>();
        bkso = new javax.swing.JComboBox<>();
        txt_harga = new javax.swing.JTextField();
        satte = new javax.swing.JCheckBox();
        bakso = new javax.swing.JCheckBox();
        txt_harga1 = new javax.swing.JTextField();
        nasigoreng = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        nasgor = new javax.swing.JComboBox<>();
        txt_harga2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        martabal = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        bangka = new javax.swing.JComboBox<>();
        txt_harga3 = new javax.swing.JTextField();
        txt_harga4 = new javax.swing.JTextField();
        ayam_bakar = new javax.swing.JCheckBox();
        bkaar = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        macha = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        mac = new javax.swing.JComboBox<>();
        txt_harga5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        kopi = new javax.swing.JCheckBox();
        kop = new javax.swing.JComboBox<>();
        txt_harga6 = new javax.swing.JTextField();
        mandi = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        man = new javax.swing.JComboBox<>();
        txt_harga7 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        teh = new javax.swing.JCheckBox();
        tarik = new javax.swing.JComboBox<>();
        txt_harga8 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(255, 235, 205));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/satee.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bakso.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nasi.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/martabak.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bakar.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Harga Rp.12.000");

        jButton1.setText("Pesan Makanan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Harga Rp.15.000");

        sate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        bkso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        txt_harga.setEditable(false);

        satte.setForeground(new java.awt.Color(0, 0, 0));
        satte.setText("sate");

        bakso.setForeground(new java.awt.Color(0, 0, 0));
        bakso.setText("Bakso");

        txt_harga1.setEditable(false);

        nasigoreng.setForeground(new java.awt.Color(0, 0, 0));
        nasigoreng.setText("NasGor");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Harga Rp.10.000");

        nasgor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        txt_harga2.setEditable(false);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/macha.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kopi.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manaadi.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tehtarek.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Minuman");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(650, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Makanan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(632, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        martabal.setForeground(new java.awt.Color(0, 0, 0));
        martabal.setText("martabak");
        martabal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                martabalActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Harga Rp.17.000");

        bangka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        txt_harga3.setEditable(false);

        txt_harga4.setEditable(false);

        ayam_bakar.setForeground(new java.awt.Color(0, 0, 0));
        ayam_bakar.setText("ayam bakar");

        bkaar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Harga Rp.22.000");

        jButton2.setText("Pesan Minum");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        macha.setForeground(new java.awt.Color(0, 0, 0));
        macha.setText("macha");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Harga Rp.9.000");

        mac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        txt_harga5.setEditable(false);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Harga Rp.11.000");

        kopi.setForeground(new java.awt.Color(0, 0, 0));
        kopi.setText("kopi");

        kop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        txt_harga6.setEditable(false);

        mandi.setForeground(new java.awt.Color(0, 0, 0));
        mandi.setText("Mandi");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Harga Rp.4.000");

        man.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        txt_harga7.setEditable(false);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Harga Rp.7.000");

        teh.setForeground(new java.awt.Color(0, 0, 0));
        teh.setText("TehTarik");

        tarik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        txt_harga8.setEditable(false);

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Nama Pemesan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel17)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(satte)
                                            .addGap(29, 29, 29)
                                            .addComponent(sate, 0, 1, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addComponent(jLabel6))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(macha)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mac, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(34, 34, 34)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_harga5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(bakso, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bkso, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_harga1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(kop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14))
                                    .addComponent(txt_harga6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(nasigoreng)
                                                .addGap(18, 18, 18)
                                                .addComponent(nasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_harga2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_harga3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(martabal)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(bangka, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel4)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txt_harga7, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(mandi)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(man, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel11)))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel20)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(teh)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tarik, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txt_harga8))))
                                .addGap(11, 11, 11)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(ayam_bakar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bkaar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_harga4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(206, 206, 206))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(kopi)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(satte)
                                .addComponent(sate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(1, 1, 1))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bakso)
                            .addComponent(bkso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nasigoreng)
                            .addComponent(nasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(martabal)
                            .addComponent(bangka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bkaar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ayam_bakar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_harga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_harga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_harga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_harga4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(macha)
                    .addComponent(mac, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kopi)
                    .addComponent(kop, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mandi)
                    .addComponent(man, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teh)
                    .addComponent(tarik, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_harga5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_harga7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_harga6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_harga8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            String tampil;
            tampil = "";
            int bayar = 0;
        if(satte.isSelected()){
            int jumlah=Integer.parseInt(sate.getSelectedItem().toString());
            int total;
            total = jumlah*12000;
            bayar = bayar + total;
        }
        else if(satte.isSelected()){
            int jumlah=Integer.parseInt(sate.getSelectedItem().toString());
            int total;
            total = jumlah*24000;
            bayar = bayar + total;
        }
        else if(satte.isSelected()){
            int jumlah=Integer.parseInt(sate.getSelectedItem().toString());
            int total;
            total = jumlah*36000;
            bayar = bayar + total;
        }
        else if(satte.isSelected()){
            int jumlah=Integer.parseInt(sate.getSelectedItem().toString());
            int total;
            total = jumlah*48000;
            bayar = bayar + total;
        }
        else if(satte.isSelected()){
            int jumlah=Integer.parseInt(sate.getSelectedItem().toString());
            int total;
            total = jumlah*60000;
            bayar = bayar + total;
        }txt_harga.setText(tampil + "Rp." + bayar);

           
        //BAKSO
        String tampill;
        tampill = "";
        int bayarr = 0;
         if(bakso.isSelected()){
            int jumlah=Integer.parseInt(bkso.getSelectedItem().toString());
            int total;
            total = jumlah*15000;
            bayarr = bayarr + total;
        }
        else if(bakso.isSelected()){
            int jumlah=Integer.parseInt(bkso.getSelectedItem().toString());
            int total;
            total = jumlah*30000;
            bayarr = bayarr + total;
        }
        else if(bakso.isSelected()){
            int jumlah=Integer.parseInt(bkso.getSelectedItem().toString());
            int total;
            total = jumlah*45000;
            bayarr = bayarr + total;
        }
        else if(bakso.isSelected()){
            int jumlah=Integer.parseInt(bkso.getSelectedItem().toString());
            int total;
            total = jumlah*60000;
            bayarr = bayarr + total;
        }
        else if(bakso.isSelected()){
            int jumlah=Integer.parseInt(bkso.getSelectedItem().toString());
            int total;
            total = jumlah*75000;
            bayarr = bayarr + total;
        }txt_harga1.setText(tampill + "Rp." + bayarr);
        
        //NASI GORENG
        String tmpil;
        tmpil = "";
        int byar = 0;
        if(nasigoreng.isSelected()){
            int jumlah=Integer.parseInt(nasgor.getSelectedItem().toString());
            int total;
            total = jumlah*10000;
            byar = byar + total;
        }
        else if(nasigoreng.isSelected()){
            int jumlah=Integer.parseInt(nasgor.getSelectedItem().toString());
            int total;
            total = jumlah*20000;
            byar = byar + total;
        }
        else if(nasigoreng.isSelected()){
            int jumlah=Integer.parseInt(nasgor.getSelectedItem().toString());
            int total;
            total = jumlah*30000;
            byar = byar + total;
        }
        else if(nasigoreng.isSelected()){
            int jumlah=Integer.parseInt(nasgor.getSelectedItem().toString());
            int total;
            total = jumlah*40000;
            byar = byar + total;
        }
        else if(nasigoreng.isSelected()){
            int jumlah=Integer.parseInt(nasgor.getSelectedItem().toString());
            int total;
            total = jumlah*50000;
            byar = byar + total;
        }txt_harga2.setText(tmpil + "Rp." + byar);
        
        //MARTABAK
        String mrtabak;
        mrtabak = "";
        int byr = 0;
        if(martabal.isSelected()){
            int jumlah=Integer.parseInt(bangka.getSelectedItem().toString());
            int total;
            total = jumlah*17000;
            byr = byr + total;
        }
        else if(martabal.isSelected()){
            int jumlah=Integer.parseInt(bangka.getSelectedItem().toString());
            int total;
            total = jumlah*34000;
            byr = byr + total;
        }
        else if(martabal.isSelected()){
            int jumlah=Integer.parseInt(bangka.getSelectedItem().toString());
            int total;
            total = jumlah*51000;
            byr = byr + total;
        }
        else if(martabal.isSelected()){
            int jumlah=Integer.parseInt(bangka.getSelectedItem().toString());
            int total;
            total = jumlah*68000;
            byr = byr + total;
        }
        else if(martabal.isSelected()){
            int jumlah=Integer.parseInt(bangka.getSelectedItem().toString());
            int total;
            total = jumlah*85000;
            byr = byr + total;
        }txt_harga3.setText(mrtabak + "Rp." + byr);
        
        //AYAM BAKAR
            String ayam;
            ayam = "";
            int by = 0;
        if(ayam_bakar.isSelected()){
            int jumlah=Integer.parseInt(bkaar.getSelectedItem().toString());
            int total;
            total = jumlah*22000;
            by = by + total;
        }
        else if(ayam_bakar.isSelected()){
            int jumlah=Integer.parseInt(bkaar.getSelectedItem().toString());
            int total;
            total = jumlah*44000;
            by = by + total;
        }
        else if(ayam_bakar.isSelected()){
            int jumlah=Integer.parseInt(bkaar.getSelectedItem().toString());
            int total;
            total = jumlah*66000;
            by = by + total;
        }
        else if(ayam_bakar.isSelected()){
            int jumlah=Integer.parseInt(bkaar.getSelectedItem().toString());
            int total;
            total = jumlah*88000;
            by = by + total;
        }
        else if(ayam_bakar.isSelected()){
            int jumlah=Integer.parseInt(bkaar.getSelectedItem().toString());
            int total;
            total = jumlah*110000;
            by = by + total;
        }txt_harga4.setText(ayam + "Rp." + by);
        try {
            String sql = "insert into harga value ('" + nama.getText() + "','"
                                                      + satte.getText() + "','"
                                                      + sate.getSelectedItem() + "','" 
                                                      + txt_harga.getText() + "','"
                                                      + bakso.getText()+ "','"
                                                      + bkso.getSelectedItem() + "','"
                                                      + txt_harga1.getText() + "','"
                                                      + nasigoreng.getText() + "','"
                                                      + nasgor.getSelectedItem() + "','"
                                                      + txt_harga2.getText() + "','"
                                                      + martabal.getText() + "','"
                                                      + bangka.getSelectedItem() + "','"
                                                      + txt_harga3.getText() + "','"
                                                      + ayam_bakar.getText() + "','"
                                                      + bkaar.getSelectedItem() + "','"
                                                      + txt_harga4.getText() + "')";
                                                              
            Connection con = (Connection) koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Harap Melakukan Pembayaran");

            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
        //MACHA
            String tampil;
            tampil = "";
            int bayar = 0;
        if(macha.isSelected()){
            int jumlah=Integer.parseInt(mac.getSelectedItem().toString());
            int total;
            total = jumlah*9000;
            bayar = bayar + total;
        }
        else if(macha.isSelected()){
            int jumlah=Integer.parseInt(mac.getSelectedItem().toString());
            int total;
            total = jumlah*18000;
            bayar = bayar + total;
        }
        else if(macha.isSelected()){
            int jumlah=Integer.parseInt(mac.getSelectedItem().toString());
            int total;
            total = jumlah*27000;
            bayar = bayar + total;
        }
        else if(macha.isSelected()){
            int jumlah=Integer.parseInt(mac.getSelectedItem().toString());
            int total;
            total = jumlah*36000;
            bayar = bayar + total;
        }
        else if(macha.isSelected()){
            int jumlah=Integer.parseInt(mac.getSelectedItem().toString());
            int total;
            total = jumlah*45000;
            bayar = bayar + total;
        }txt_harga5.setText(tampil + "Rp." + bayar);

           
        //KOPI
        String tampill;
        tampill = "";
        int bayarr = 0;
         if(kopi.isSelected()){
            int jumlah=Integer.parseInt(kop.getSelectedItem().toString());
            int total;
            total = jumlah*11000;
            bayarr = bayarr + total;
        }
        else if(kopi.isSelected()){
            int jumlah=Integer.parseInt(kop.getSelectedItem().toString());
            int total;
            total = jumlah*22000;
            bayarr = bayarr + total;
        }
        else if(kopi.isSelected()){
            int jumlah=Integer.parseInt(kop.getSelectedItem().toString());
            int total;
            total = jumlah*33000;
            bayarr = bayarr + total;
        }
        else if(kopi.isSelected()){
            int jumlah=Integer.parseInt(kop.getSelectedItem().toString());
            int total;
            total = jumlah*44000;
            bayarr = bayarr + total;
        }
        else if(kopi.isSelected()){
            int jumlah=Integer.parseInt(kop.getSelectedItem().toString());
            int total;
            total = jumlah*55000;
            bayarr = bayarr + total;
        }txt_harga6.setText(tampill + "Rp." + bayarr);
        
        //MANDI
        String tmpil;
        tmpil = "";
        int byar = 0;
        if(mandi.isSelected()){
            int jumlah=Integer.parseInt(man.getSelectedItem().toString());
            int total;
            total = jumlah*4000;
            byar = byar + total;
        }
        else if(mandi.isSelected()){
            int jumlah=Integer.parseInt(man.getSelectedItem().toString());
            int total;
            total = jumlah*8000;
            byar = byar + total;
        }
        else if(mandi.isSelected()){
            int jumlah=Integer.parseInt(man.getSelectedItem().toString());
            int total;
            total = jumlah*12000;
            byar = byar + total;
        }
        else if(mandi.isSelected()){
            int jumlah=Integer.parseInt(man.getSelectedItem().toString());
            int total;
            total = jumlah*16000;
            byar = byar + total;
        }
        else if(mandi.isSelected()){
            int jumlah=Integer.parseInt(man.getSelectedItem().toString());
            int total;
            total = jumlah*20000;
            byar = byar + total;
        }txt_harga7.setText(tmpil + "Rp." + byar);
        
        //TEH TARIK
        String mrtabak;
        mrtabak = "";
        int byr = 0;
        if(teh.isSelected()){
            int jumlah=Integer.parseInt(tarik.getSelectedItem().toString());
            int total;
            total = jumlah*7000;
            byr = byr + total;
        }
        else if(teh.isSelected()){
            int jumlah=Integer.parseInt(tarik.getSelectedItem().toString());
            int total;
            total = jumlah*14000;
            byr = byr + total;
        }
        else if(teh.isSelected()){
            int jumlah=Integer.parseInt(tarik.getSelectedItem().toString());
            int total;
            total = jumlah*21000;
            byr = byr + total;
        }
        else if(teh.isSelected()){
            int jumlah=Integer.parseInt(tarik.getSelectedItem().toString());
            int total;
            total = jumlah*28000;
            byr = byr + total;
        }
        else if(teh.isSelected()){
            int jumlah=Integer.parseInt(tarik.getSelectedItem().toString());
            int total;
            total = jumlah*35000;
            byr = byr + total;
        }txt_harga8.setText(mrtabak + "Rp." + byr);
        
        
        try {
            String sql = "insert into minuman value ('" + nama.getText() +"','"
                                                      + macha.getText() + "','"
                                                      + mac.getSelectedItem() + "','" 
                                                      + txt_harga5.getText() + "','"
                                                      + kopi.getText()+ "','"
                                                      + kop.getSelectedItem() + "','"
                                                      + txt_harga6.getText() + "','"
                                                      + mandi.getText() + "','"
                                                      + man.getSelectedItem() + "','"
                                                      + txt_harga7.getText() + "','"
                                                      + teh.getText() + "','"
                                                      + tarik.getSelectedItem() + "','"
                                                      + txt_harga8.getText() +"')";
                                                              
            Connection con = (Connection) koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Harap Melakukan Pembayaran");

            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void martabalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_martabalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_martabalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ayam_bakar;
    private javax.swing.JCheckBox bakso;
    private javax.swing.JComboBox<String> bangka;
    private javax.swing.JComboBox<String> bkaar;
    private javax.swing.JComboBox<String> bkso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> kop;
    private javax.swing.JCheckBox kopi;
    private javax.swing.JComboBox<String> mac;
    private javax.swing.JCheckBox macha;
    private javax.swing.JComboBox<String> man;
    private javax.swing.JCheckBox mandi;
    private javax.swing.JCheckBox martabal;
    private javax.swing.JTextField nama;
    private javax.swing.JComboBox<String> nasgor;
    private javax.swing.JCheckBox nasigoreng;
    private javax.swing.JComboBox<String> sate;
    private javax.swing.JCheckBox satte;
    private javax.swing.JComboBox<String> tarik;
    private javax.swing.JCheckBox teh;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_harga1;
    private javax.swing.JTextField txt_harga2;
    private javax.swing.JTextField txt_harga3;
    private javax.swing.JTextField txt_harga4;
    private javax.swing.JTextField txt_harga5;
    private javax.swing.JTextField txt_harga6;
    private javax.swing.JTextField txt_harga7;
    private javax.swing.JTextField txt_harga8;
    // End of variables declaration//GEN-END:variables
}
